//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSS_ASPWebForms.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditUser_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditUser_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSS_ASPWebForms.App_LocalResources.EditUser.aspx", typeof(EditUser_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Picture....
        /// </summary>
        internal static string AddPicture_Text {
            get {
                return ResourceManager.GetString("AddPicture.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow.
        /// </summary>
        internal static string Allow_HeaderText {
            get {
                return ResourceManager.GetString("Allow.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Roles : .
        /// </summary>
        internal static string AssignedRoles_Text {
            get {
                return ResourceManager.GetString("AssignedRoles.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department : .
        /// </summary>
        internal static string Department_Text {
            get {
                return ResourceManager.GetString("Department.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more fields are not valid. please recheck the following fields.
        /// </summary>
        internal static string ErrorMsg {
            get {
                return ResourceManager.GetString("ErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function &apos;SaveUser&apos; can not be called at this time.
        /// </summary>
        internal static string ErrorSaveUser {
            get {
                return ResourceManager.GetString("ErrorSaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password : .
        /// </summary>
        internal static string Password_Text {
            get {
                return ResourceManager.GetString("Password.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role_HeaderText {
            get {
                return ResourceManager.GetString("Role.HeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Enabled : .
        /// </summary>
        internal static string UserEnabled_Text {
            get {
                return ResourceManager.GetString("UserEnabled.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username : .
        /// </summary>
        internal static string Username_Text {
            get {
                return ResourceManager.GetString("Username.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User info is already opened by another user. the user info will be opened as read only..
        /// </summary>
        internal static string UserOpenMsg {
            get {
                return ResourceManager.GetString("UserOpenMsg", resourceCulture);
            }
        }
    }
}
